export default [
 { eloado:"Coldplay", cim:"A Sky Full of Stars", ev:2014, album:"Ghost Stories" },
 { eloado:"Lorde", cim:"A World Alone", ev:2013, album:"Pure Heroine" },
 { eloado:"Coldplay", cim:"Adventure of a Lifetime", ev:2015, album:"A Head Full of Dreams" },
 { eloado:"Lady Gaga", cim:"Alejandro", ev:2009, album:"The Fame Monster" },
 { eloado:"Taylor Swift", cim:"All Too Well", ev:2012, album:"Red" },
 { eloado:"Kendrick Lamar", cim:"Alright", ev:2015, album:"To Pimp a Butterfly" },
 { eloado:"Lady Gaga", cim:"Bad Romance", ev:2009, album:"The Fame Monster" },
 { eloado:"Drake", cim:"Best I Ever Had", ev:2009, album:"So Far Gone" },
 { eloado:"Kendrick Lamar", cim:"Bitch, Don't Kill My Vibe", ev:2012, album:"good kid, m.A.A.d city" },
 { eloado:"Taylor Swift", cim:"Blank Space", ev:2014, album:"1989" },
 { eloado:"Lady Gaga", cim:"Born This Way", ev:2011, album:"Born This Way" },
 { eloado:"Lorde", cim:"Buzzcut Season", ev:2013, album:"Pure Heroine" },
 { eloado:"Ed Sheeran", cim:"Castle on the Hill", ev:2017, album:"÷ (Divide)" },
 { eloado:"Adele", cim:"Chasing Pavements", ev:2008, album:"19" },
 { eloado:"Coldplay", cim:"Clocks", ev:2002, album:"A Rush of Blood to the Head" },
 { eloado:"Beyoncé", cim:"Crazy in Love", ev:2003, album:"Dangerously in Love" },
 { eloado:"Ed Sheeran", cim:"Dive", ev:2017, album:"÷ (Divide)" },
 { eloado:"Kendrick Lamar", cim:"DNA.", ev:2017, album:"DAMN." },
 { eloado:"Adele", cim:"Don't You Remember", ev:2011, album:"21" },
 { eloado:"Beyoncé", cim:"Drunk in Love", ev:2013, album:"Beyoncé" },
 { eloado:"Taylor Swift", cim:"Fearless", ev:2008, album:"Fearless" },
 { eloado:"Coldplay", cim:"Fix You", ev:2005, album:"X&Y" },
 { eloado:"Beyoncé", cim:"Formation", ev:2016, album:"Lemonade" },
 { eloado:"Ed Sheeran", cim:"Galway Girl", ev:2017, album:"÷ (Divide)" },
 { eloado:"Drake", cim:"God's Plan", ev:2018, album:"Scary Hours 2 (EP)" },
 { eloado:"Lorde", cim:"Green Light", ev:2017, album:"Melodrama" },
 { eloado:"Beyoncé", cim:"Halo", ev:2008, album:"I Am... Sasha Fierce" },
 { eloado:"Ed Sheeran", cim:"Happier", ev:2017, album:"÷ (Divide)" },
 { eloado:"Lorde", cim:"Hard Feelings/Loveless", ev:2017, album:"Melodrama" },
 { eloado:"Adele", cim:"Hello", ev:2015, album:"25" },
 { eloado:"Lorde", cim:"Homemade Dynamite", ev:2017, album:"Melodrama" },
 { eloado:"Drake", cim:"Hotline Bling", ev:2015, album:"Views" },
 { eloado:"Kendrick Lamar", cim:"HUMBLE.", ev:2017, album:"DAMN." },
 { eloado:"Coldplay", cim:"Hymn for the Weekend", ev:2016, album:"A Head Full of Dreams" },
 { eloado:"Taylor Swift", cim:"I Knew You Were Trouble", ev:2012, album:"Red" },
 { eloado:"Ed Sheeran", cim:"I See Fire", ev:2013, album:"The Hobbit: The Desolation of Smaug (Soundtrack)" },
 { eloado:"Beyoncé", cim:"If I Were a Boy", ev:2008, album:"I Am... Sasha Fierce" },
 { eloado:"Drake", cim:"In My Feelings", ev:2018, album:"Scorpion" },
 { eloado:"Beyoncé", cim:"Irreplaceable", ev:2006, album:"B'Day" },
 { eloado:"Lady Gaga", cim:"Just Dance", ev:2008, album:"The Fame" },
 { eloado:"Kendrick Lamar", cim:"King Kunta", ev:2015, album:"To Pimp a Butterfly" },
 { eloado:"Lorde", cim:"Liability", ev:2017, album:"Melodrama" },
 { eloado:"Beyoncé", cim:"Love On Top", ev:2011, album:"4" },
 { eloado:"Taylor Swift", cim:"Love Story", ev:2008, album:"Fearless" },
 { eloado:"Lady Gaga", cim:"Lovegame", ev:2008, album:"The Fame" },
 { eloado:"Kendrick Lamar", cim:"M.A.A.d City", ev:2012, album:"good kid, m.A.A.d city" },
 { eloado:"Adele", cim:"Make You Feel My Love", ev:2008, album:"19" },
 { eloado:"Lady Gaga", cim:"Marry the Night", ev:2011, album:"Born This Way" },
 { eloado:"Drake", cim:"Marvins Room", ev:2011, album:"Take Care" },
 { eloado:"Kendrick Lamar", cim:"Money Trees", ev:2012, album:"good kid, m.A.A.d city" },
 { eloado:"Drake", cim:"Nonstop", ev:2018, album:"Scorpion" },
 { eloado:"Drake", cim:"One Dance", ev:2016, album:"Views" },
 { eloado:"Lady Gaga", cim:"Paparazzi", ev:2008, album:"The Fame" },
 { eloado:"Coldplay", cim:"Paradise", ev:2011, album:"Mylo Xyloto" },
 { eloado:"Ed Sheeran", cim:"Perfect", ev:2017, album:"÷ (Divide)" },
 { eloado:"Lorde", cim:"Perfect Places", ev:2017, album:"Melodrama" },
 { eloado:"Ed Sheeran", cim:"Photograph", ev:2014, album:"× (Multiply)" },
 { eloado:"Kendrick Lamar", cim:"Poetic Justice", ev:2012, album:"good kid, m.A.A.d city" },
 { eloado:"Lady Gaga", cim:"Poker Face", ev:2008, album:"The Fame" },
 { eloado:"Lorde", cim:"Ribs", ev:2013, album:"Pure Heroine" },
 { eloado:"Adele", cim:"Rolling in the Deep", ev:2011, album:"21" },
 { eloado:"Lorde", cim:"Royals", ev:2013, album:"Pure Heroine" },
 { eloado:"Adele", cim:"Rumour Has It", ev:2011, album:"21" },
 { eloado:"Beyoncé", cim:"Run the World (Girls)", ev:2011, album:"4" },
 { eloado:"Adele", cim:"Set Fire to the Rain", ev:2011, album:"21" },
 { eloado:"Taylor Swift", cim:"Shake It Off", ev:2014, album:"1989" },
 { eloado:"Ed Sheeran", cim:"Shape of You", ev:2017, album:"÷ (Divide)" },
 { eloado:"Beyoncé", cim:"Single Ladies (Put a Ring on It)", ev:2008, album:"I Am... Sasha Fierce" },
 { eloado:"Adele", cim:"Skyfall", ev:2012, album:"Skyfall (Single)" },
 { eloado:"Adele", cim:"Someone Like You", ev:2011, album:"21" },
 { eloado:"Lady Gaga", cim:"Speechless", ev:2008, album:"The Fame" },
 { eloado:"Coldplay", cim:"Speed of Sound", ev:2005, album:"X&Y" },
 { eloado:"Drake", cim:"Started From the Bottom", ev:2013, album:"Nothing Was the Same" },
 { eloado:"Taylor Swift", cim:"Style", ev:2014, album:"1989" },
 { eloado:"Beyoncé", cim:"Sweet Dreams", ev:2008, album:"I Am... Sasha Fierce" },
 { eloado:"Kendrick Lamar", cim:"Swimming Pools (Drank)", ev:2012, album:"good kid, m.A.A.d city" },
 { eloado:"Drake", cim:"Take Care", ev:2011, album:"Take Care" },
 { eloado:"Lorde", cim:"Team", ev:2013, album:"Pure Heroine" },
 { eloado:"Lorde", cim:"Tennis Court", ev:2013, album:"Pure Heroine" },
 { eloado:"Kendrick Lamar", cim:"The Blacker the Berry", ev:2015, album:"To Pimp a Butterfly" },
 { eloado:"Lady Gaga", cim:"The Edge of Glory", ev:2011, album:"Born This Way" },
 { eloado:"Lorde", cim:"The Louvre", ev:2017, album:"Melodrama" },
 { eloado:"Coldplay", cim:"The Scientist", ev:2002, album:"A Rush of Blood to the Head" },
 { eloado:"Ed Sheeran", cim:"Thinking Out Loud", ev:2014, album:"× (Multiply)" },
 { eloado:"Coldplay", cim:"Viva la Vida", ev:2008, album:"Viva la Vida or Death and All His Friends" },
 { eloado:"Taylor Swift", cim:"We Are Never Ever Getting Back Together", ev:2012, album:"Red" },
 { eloado:"Adele", cim:"When We Were Young", ev:2015, album:"25" },
 { eloado:"Taylor Swift", cim:"Wildest Dreams", ev:2015, album:"1989" },
 { eloado:"Coldplay", cim:"Yellow", ev:2000, album:"Parachutes" },
 { eloado:"Taylor Swift", cim:"You Belong with Me", ev:2008, album:"Fearless" }
]