export default [
 { nev:"7UP", kategoria:"Szénsavas", ml:500, kcal:200 },
 { nev:"7UP Free", kategoria:"Cukormentes", ml:500, kcal:0 },
 { nev:"Alpesi 100%-os Alma", kategoria:"Gyümölcslé", ml:1000, kcal:460 },
 { nev:"Bio zöldség- és gyümölcslé", kategoria:"Gyümölcslé", ml:250, kcal:130 },
 { nev:"Coca-Cola", kategoria:"Szénsavas", ml:500, kcal:210 },
 { nev:"Coca-Cola Zero", kategoria:"Cukormentes", ml:500, kcal:0 },
 { nev:"Don Simon 100%-os Alma", kategoria:"Gyümölcslé", ml:1000, kcal:450 },
 { nev:"Fanta", kategoria:"Szénsavas", ml:500, kcal:200 },
 { nev:"Fanta Zero", kategoria:"Cukormentes", ml:500, kcal:0 },
 { nev:"Frútkó Narancs", kategoria:"Szénsavas", ml:500, kcal:220 },
 { nev:"Fruttissimo", kategoria:"Gyümölcslé", ml:200, kcal:90 },
 { nev:"Kubus Fanta", kategoria:"Szénsavas", ml:200, kcal:80 },
 { nev:"Minute Maid Narancs", kategoria:"Gyümölcslé", ml:1000, kcal:420 },
 { nev:"Mizo Nektár Narancs", kategoria:"Gyümölcslé", ml:1000, kcal:480 },
 { nev:"Pepsi", kategoria:"Szénsavas", ml:500, kcal:220 },
 { nev:"Pepsi Max", kategoria:"Cukormentes", ml:500, kcal:0 },
 { nev:"Schweppes Light", kategoria:"Cukormentes", ml:500, kcal:0 },
 { nev:"Schweppes Tonic Water", kategoria:"Szénsavas", ml:500, kcal:180 },
 { nev:"Sprite", kategoria:"Szénsavas", ml:500, kcal:200 },
 { nev:"Sprite Zero", kategoria:"Cukormentes", ml:500, kcal:0 },
 { nev:"Tonik Zero", kategoria:"Cukormentes", ml:500, kcal:0 },
 { nev:"Tropicana 100%-os narancslé", kategoria:"Gyümölcslé", ml:1000, kcal:430 }
]