export default [
 { id:1, nev:"Acre Time", rov:"ACT", ido:"UTC-05:00" },
 { id:2, nev:"Afghanistan Time", rov:"AFT", ido:"UTC+04:30" },
 { id:3, nev:"Alaska Daylight Time", rov:"AKDT", ido:"UTC-08:00" },
 { id:4, nev:"Alaska Standard Time", rov:"AKST", ido:"UTC-09:00" },
 { id:5, nev:"Alma-Ata Time", rov:"ALMT", ido:"UTC+06:00" },
 { id:6, nev:"Amazon Summer Time", rov:"AMST", ido:"UTC-03:00" },
 { id:7, nev:"Amazon Time", rov:"AMT", ido:"UTC-04:00" },
 { id:8, nev:"Anadyr Time", rov:"ANAT", ido:"UTC+12:00" },
 { id:9, nev:"Aqtobe Time", rov:"AQTT", ido:"UTC+05:00" },
 { id:10, nev:"Arabia Standard Time", rov:"AST", ido:"UTC+03:00" },
 { id:11, nev:"Argentina Time", rov:"ART", ido:"UTC-03:00" },
 { id:12, nev:"Armenia Time", rov:"AMT", ido:"UTC+04:00" },
 { id:13, nev:"Atlantic Daylight Time", rov:"ADT", ido:"UTC-03:00" },
 { id:14, nev:"Atlantic Standard Time", rov:"AST", ido:"UTC-04:00" },
 { id:15, nev:"Australian Central Daylight Time", rov:"ACDT", ido:"UTC+10:30" },
 { id:16, nev:"Australian Central Standard Time", rov:"ACST", ido:"UTC+09:30" },
 { id:17, nev:"Australian Central Western Time", rov:"ACWT", ido:"UTC+08:45" },
 { id:18, nev:"Australian Eastern Daylight Time", rov:"AEDT", ido:"UTC+11:00" },
 { id:19, nev:"Australian Eastern Standard Time", rov:"AEST", ido:"UTC+10:00" },
 { id:20, nev:"Australian Western Standard Time", rov:"AWST", ido:"UTC+08:00" },
 { id:21, nev:"Azerbaijan Time", rov:"AZT", ido:"UTC+04:00" },
 { id:22, nev:"Azores Summer Time", rov:"AZOST", ido:"UTC+00:00" },
 { id:23, nev:"Azores Time", rov:"AZOT", ido:"UTC-01:00" },
 { id:24, nev:"Baker Island Time", rov:"BIT", ido:"UTC-12:00" },
 { id:25, nev:"Bangladesh Standard Time", rov:"BST", ido:"UTC+06:00" },
 { id:26, nev:"Bhutan Time", rov:"BTT", ido:"UTC+06:00" },
 { id:27, nev:"Bolivia Time", rov:"BOT", ido:"UTC-04:00" },
 { id:28, nev:"Bougainville Standard Time", rov:"BST", ido:"UTC+11:00" },
 { id:29, nev:"Brasilia Summer Time", rov:"BRST", ido:"UTC-02:00" },
 { id:30, nev:"Brasilia Time", rov:"BRT", ido:"UTC-03:00" },
 { id:31, nev:"British Summer Time", rov:"BST", ido:"UTC+01:00" },
 { id:32, nev:"Brunei Darussalam Time", rov:"BNT", ido:"UTC+08:00" },
 { id:33, nev:"Cape Verde Time", rov:"CVT", ido:"UTC-01:00" },
 { id:34, nev:"Central Africa Time", rov:"CAT", ido:"UTC+02:00" },
 { id:35, nev:"Central Daylight Time", rov:"CDT", ido:"UTC-05:00" },
 { id:36, nev:"Central European Summer Time", rov:"CEST", ido:"UTC+02:00" },
 { id:37, nev:"Central European Time", rov:"CET", ido:"UTC+01:00" },
 { id:38, nev:"Central Indonesian Time", rov:"WITA", ido:"UTC+08:00" },
 { id:39, nev:"Central Standard Time", rov:"CST", ido:"UTC-06:00" },
 { id:40, nev:"Chamorro Standard Time", rov:"ChST", ido:"UTC+10:00" },
 { id:41, nev:"Chatham Island Daylight Time", rov:"CHADT", ido:"UTC+13:45" },
 { id:42, nev:"Chatham Island Standard Time", rov:"CHAST", ido:"UTC+12:45" },
 { id:43, nev:"Chile Standard Time", rov:"CLT", ido:"UTC-04:00" },
 { id:44, nev:"Chile Summer Time", rov:"CLST", ido:"UTC-03:00" },
 { id:45, nev:"China Standard Time", rov:"CST", ido:"UTC+08:00" },
 { id:46, nev:"Choibalsan Time", rov:"CHOT", ido:"UTC+08:00" },
 { id:47, nev:"Christmas Island Time", rov:"CXT", ido:"UTC+07:00" },
 { id:48, nev:"Chuuk Time", rov:"CHUT", ido:"UTC+10:00" },
 { id:49, nev:"Cocos Islands Time", rov:"CCT", ido:"UTC+06:30" },
 { id:50, nev:"Colombia Time", rov:"COT", ido:"UTC-05:00" },
 { id:51, nev:"Cook Island Time", rov:"CKT", ido:"UTC-10:00" },
 { id:52, nev:"Cuba Daylight Time", rov:"CDT", ido:"UTC-04:00" },
 { id:53, nev:"Cuba Standard Time", rov:"CST", ido:"UTC-05:00" },
 { id:54, nev:"Davis Time", rov:"DAVT", ido:"UTC+07:00" },
 { id:55, nev:"Dumont-d'Urville Time", rov:"DDUT", ido:"UTC+10:00" },
 { id:56, nev:"East Greenland Time", rov:"EGT", ido:"UTC-01:00" },
 { id:57, nev:"East Timor Time", rov:"TLT", ido:"UTC+09:00" },
 { id:58, nev:"Easter Island Standard Time", rov:"EAST", ido:"UTC-06:00" },
 { id:59, nev:"Easter Island Summer Time", rov:"EASST", ido:"UTC-05:00" },
 { id:60, nev:"Eastern Africa Time", rov:"EAT", ido:"UTC+03:00" },
 { id:61, nev:"Eastern Daylight Time", rov:"EDT", ido:"UTC-04:00" },
 { id:62, nev:"Eastern European Summer Time", rov:"EEST", ido:"UTC+03:00" },
 { id:63, nev:"Eastern European Time", rov:"EET", ido:"UTC+02:00" },
 { id:64, nev:"Eastern Greenland Summer Time", rov:"EGST", ido:"UTC+00:00" },
 { id:65, nev:"Eastern Indonesian Time", rov:"WIT", ido:"UTC+09:00" },
 { id:66, nev:"Eastern Standard Time", rov:"EST", ido:"UTC-05:00" },
 { id:67, nev:"Ecuador Time", rov:"ECT", ido:"UTC-05:00" },
 { id:68, nev:"Falkland Islands Time", rov:"FKT", ido:"UTC-04:00" },
 { id:69, nev:"Falkland Islands Summer Time", rov:"FKST", ido:"UTC-03:00" },
 { id:70, nev:"Fernando de Noronha Time", rov:"FNT", ido:"UTC-02:00" },
 { id:71, nev:"Fiji Summer Time", rov:"FJST", ido:"UTC+13:00" },
 { id:72, nev:"Fiji Time", rov:"FJT", ido:"UTC+12:00" },
 { id:73, nev:"French Guiana Time", rov:"GFT", ido:"UTC-03:00" },
 { id:74, nev:"French Southern and Antarctic Time", rov:"TFT", ido:"UTC+05:00" },
 { id:75, nev:"Galapagos Time", rov:"GALT", ido:"UTC-06:00" },
 { id:76, nev:"Gambier Time", rov:"GAMT", ido:"UTC-09:00" },
 { id:77, nev:"Georgia Standard Time", rov:"GET", ido:"UTC+04:00" },
 { id:78, nev:"Gilbert Island Time", rov:"GILT", ido:"UTC+12:00" },
 { id:79, nev:"Greenwich Mean Time", rov:"GMT", ido:"UTC+00:00" },
 { id:80, nev:"Gulf Standard Time", rov:"GST", ido:"UTC+04:00" },
 { id:81, nev:"Guyana Time", rov:"GYT", ido:"UTC-04:00" },
 { id:82, nev:"Hawaii-Aleutian Daylight Time", rov:"HADT", ido:"UTC-09:00" },
 { id:83, nev:"Hawaii-Aleutian Standard Time", rov:"HAST", ido:"UTC-10:00" },
 { id:84, nev:"Hong Kong Time", rov:"HKT", ido:"UTC+08:00" },
 { id:85, nev:"Hovd Summer Time", rov:"HOVST", ido:"UTC+08:00" },
 { id:86, nev:"Hovd Time", rov:"HOVT", ido:"UTC+07:00" },
 { id:87, nev:"Indian Chagos Time", rov:"IOT", ido:"UTC+06:00" },
 { id:88, nev:"Indian Standard Time", rov:"IST", ido:"UTC+05:30" },
 { id:89, nev:"Indochina Time", rov:"ICT", ido:"UTC+07:00" },
 { id:90, nev:"Iran Daylight Time", rov:"IRDT", ido:"UTC+04:30" },
 { id:91, nev:"Iran Standard Time", rov:"IRST", ido:"UTC+03:30" },
 { id:92, nev:"Irish Standard Time", rov:"IST", ido:"UTC+01:00" },
 { id:93, nev:"Irkutsk Time", rov:"IRKT", ido:"UTC+08:00" },
 { id:94, nev:"Israel Daylight Time", rov:"IDT", ido:"UTC+03:00" },
 { id:95, nev:"Israel Standard Time", rov:"IST", ido:"UTC+02:00" },
 { id:96, nev:"Japan Standard Time", rov:"JST", ido:"UTC+09:00" },
 { id:97, nev:"Kaliningrad Time", rov:"USZ1", ido:"UTC+02:00" },
 { id:98, nev:"Kamchatka Time", rov:"PETT", ido:"UTC+12:00" },
 { id:99, nev:"Korea Standard Time", rov:"KST", ido:"UTC+09:00" },
 { id:100, nev:"Kosrae Time", rov:"KOST", ido:"UTC+11:00" },
 { id:101, nev:"Krasnoyarsk Time", rov:"KRAT", ido:"UTC+07:00" },
 { id:102, nev:"Kyrgyzstan Time", rov:"KGT", ido:"UTC+06:00" },
 { id:103, nev:"Line Islands Time", rov:"LINT", ido:"UTC+14:00" },
 { id:104, nev:"Lord Howe Daylight Time", rov:"LHDT", ido:"UTC+11:00" },
 { id:105, nev:"Lord Howe Standard Time", rov:"LHST", ido:"UTC+10:30" },
 { id:106, nev:"Magadan Time", rov:"MAGT", ido:"UTC+11:00" },
 { id:107, nev:"Malaysia Standard Time", rov:"MST", ido:"UTC+08:00" },
 { id:108, nev:"Maldives Time", rov:"MVT", ido:"UTC+05:00" },
 { id:109, nev:"Marquesas Time", rov:"MART", ido:"UTC-09:00" },
 { id:110, nev:"Marshall Islands Time", rov:"MHT", ido:"UTC+12:00" },
 { id:111, nev:"Mauritius Time", rov:"MUT", ido:"UTC+04:00" },
 { id:112, nev:"Mawson Time", rov:"MAWT", ido:"UTC+05:00" },
 { id:113, nev:"Moscow Time", rov:"MSK", ido:"UTC+03:00" },
 { id:114, nev:"Mountain Daylight Time", rov:"MDT", ido:"UTC-06:00" },
 { id:115, nev:"Mountain Standard Time", rov:"MST", ido:"UTC-07:00" },
 { id:116, nev:"Myanmar Standard Time", rov:"MMT", ido:"UTC+06:30" },
 { id:117, nev:"Nauru Time", rov:"NRT", ido:"UTC+12:00" },
 { id:118, nev:"Nepal Time", rov:"NPT", ido:"UTC+05:45" },
 { id:119, nev:"New Caledonia Time", rov:"NCT", ido:"UTC+11:00" },
 { id:120, nev:"New Zealand Daylight Time", rov:"NZDT", ido:"UTC+13:00" },
 { id:121, nev:"New Zealand Standard Time", rov:"NZST", ido:"UTC+12:00" },
 { id:122, nev:"Newfoundland Daylight Time", rov:"NDT", ido:"UTC-02:30" },
 { id:123, nev:"Newfoundland Standard Time", rov:"NST", ido:"UTC-03:30" },
 { id:124, nev:"Niue Time", rov:"NUT", ido:"UTC-11:00" },
 { id:125, nev:"Norfolk Time", rov:"NFT", ido:"UTC+11:00" },
 { id:126, nev:"Omsk Time", rov:"OMST", ido:"UTC+06:00" },
 { id:127, nev:"Oral Time", rov:"ORAT", ido:"UTC+05:00" },
 { id:128, nev:"Pacific Daylight Time", rov:"PDT", ido:"UTC-07:00" },
 { id:129, nev:"Pacific Standard Time", rov:"PST", ido:"UTC-08:00" },
 { id:130, nev:"Pakistan Standard Time", rov:"PKT", ido:"UTC+05:00" },
 { id:131, nev:"Palau Time", rov:"PWT", ido:"UTC+09:00" },
 { id:132, nev:"Papua New Guinea Time", rov:"PGT", ido:"UTC+10:00" },
 { id:133, nev:"Paraguay Summer Time", rov:"PYST", ido:"UTC-03:00" },
 { id:134, nev:"Paraguay Time", rov:"PYT", ido:"UTC-04:00" },
 { id:135, nev:"Peru Time", rov:"PET", ido:"UTC-05:00" },
 { id:136, nev:"Philippine Standard Time", rov:"PST", ido:"UTC+08:00" },
 { id:137, nev:"Phoenix Island Time", rov:"PHOT", ido:"UTC+13:00" },
 { id:138, nev:"Pierre & Miquelion Daylight Time", rov:"PMDT", ido:"UTC-02:00" },
 { id:139, nev:"Pierre & Miquelion Standard Time", rov:"PMST", ido:"UTC-03:00" },
 { id:140, nev:"Pitcairn Standard Time", rov:"PST", ido:"UTC-08:00" },
 { id:141, nev:"Pohnpei Standard Time", rov:"PONT", ido:"UTC+11:00" },
 { id:142, nev:"Pyongyang Time", rov:"PYT", ido:"UTC+08:30" },
 { id:143, nev:"Qyzylorda Time", rov:"QYZT", ido:"UTC+06:00" },
 { id:144, nev:"Reunion Time", rov:"RET", ido:"UTC+04:00" },
 { id:145, nev:"Sakhalin Time", rov:"SAKT", ido:"UTC+11:00" },
 { id:146, nev:"Samara Time", rov:"SAMT", ido:"UTC+04:00" },
 { id:147, nev:"Samoa Standard Time", rov:"SST", ido:"UTC-11:00" },
 { id:148, nev:"Seychelles Time", rov:"SCT", ido:"UTC+04:00" },
 { id:149, nev:"Singapore Standard Time", rov:"SST", ido:"UTC+08:00" },
 { id:150, nev:"Solomon Islands Time", rov:"SBT", ido:"UTC+11:00" },
 { id:151, nev:"South Africa Standard Time", rov:"SAST", ido:"UTC+02:00" },
 { id:152, nev:"South Georgia Time", rov:"GST", ido:"UTC-02:00" },
 { id:153, nev:"Srednekolymsk Time", rov:"SRET", ido:"UTC+11:00" },
 { id:154, nev:"Suriname Time", rov:"SRT", ido:"UTC-03:00" },
 { id:155, nev:"Tahiti Time", rov:"TAHT", ido:"UTC-10:00" },
 { id:156, nev:"Tajikistan Time", rov:"TJT", ido:"UTC+05:00" },
 { id:157, nev:"Tokelau Time", rov:"TKT", ido:"UTC+13:00" },
 { id:158, nev:"Tonga Summer Time", rov:"TOST", ido:"UTC+14:00" },
 { id:159, nev:"Tonga Time", rov:"TOT", ido:"UTC+13:00" },
 { id:160, nev:"Turkey Time", rov:"TRT", ido:"UTC+03:00" },
 { id:161, nev:"Turkmenistan Time", rov:"TMT", ido:"UTC+05:00" },
 { id:162, nev:"Tuvalu Time", rov:"TVT", ido:"UTC+12:00" },
 { id:163, nev:"Ulaanbaatar Time", rov:"ULAT", ido:"UTC+08:00" },
 { id:164, nev:"Uruguay Summer Time", rov:"UYST", ido:"UTC-02:00" },
 { id:165, nev:"Uruguay Time", rov:"UYT", ido:"UTC-03:00" },
 { id:166, nev:"Uzbekistan Time", rov:"UZT", ido:"UTC+05:00" },
 { id:167, nev:"Vanuatu Time", rov:"VUT", ido:"UTC+11:00" },
 { id:168, nev:"Venezuelan Standard Time", rov:"VET", ido:"UTC-04:00" },
 { id:169, nev:"Vladivostok Time", rov:"VLAT", ido:"UTC+10:00" },
 { id:170, nev:"Vostok Time", rov:"VOST", ido:"UTC+06:00" },
 { id:171, nev:"Wake Time", rov:"WAKT", ido:"UTC+12:00" },
 { id:172, nev:"Wallis and Futuna Time", rov:"WFT", ido:"UTC+12:00" },
 { id:173, nev:"West Africa Summer Time", rov:"WAST", ido:"UTC+02:00" },
 { id:174, nev:"West Africa Time", rov:"WAT", ido:"UTC+01:00" },
 { id:175, nev:"West Greenland Time", rov:"WGT", ido:"UTC-03:00" },
 { id:176, nev:"West Samoa Time", rov:"WST", ido:"UTC+14:00" },
 { id:177, nev:"Western European Summer Time", rov:"WEST", ido:"UTC+01:00" },
 { id:178, nev:"Western European Time", rov:"WET", ido:"UTC+00:00" },
 { id:179, nev:"Western Greenland Summer Time", rov:"WGST", ido:"UTC-02:00" },
 { id:180, nev:"Western Indonesian Time", rov:"WIT", ido:"UTC+07:00" },
 { id:181, nev:"Yakutsk Time", rov:"YAKT", ido:"UTC+09:00" },
 { id:182, nev:"Yekatienburg Time", rov:"YEKT", ido:"UTC+05:00" }
]