export default [
 { kategoria:"Bútorok", nev:"Ágykeret", ar:54900, marka:"Lepo", leiras:"Stabil, modern dizájn." },
 { kategoria:"Elektronikai termékek", nev:"Digitális fényképezőgép", ar:149900, marka:"Canon", leiras:"Professzionális fényképezéshez, több objektívvel." },
 { kategoria:"Konyhai eszközök", nev:"Edénykészlet", ar:34990, marka:"Castey", leiras:"Nagy teherbírású, több darabos készlet." },
 { kategoria:"Sportfelszerelések", nev:"Edzőgépek", ar:119990, marka:"Life Fitness", leiras:"Profi edzőgépek otthoni használatra." },
 { kategoria:"Bútorok", nev:"Étkezőasztal", ar:24990, marka:"IKEA", leiras:"Stílusos, praktikus asztal étkezéshez." },
 { kategoria:"Sportfelszerelések", nev:"Futócipő", ar:29990, marka:"Nike", leiras:"Könnyű és kényelmes futáshoz." },
 { kategoria:"Elektronikai termékek", nev:"Fülhallgató", ar:19990, marka:"Sennheiser", leiras:"Minőségi hangzás, kényelmes viselet." },
 { kategoria:"Sportfelszerelések", nev:"Gravitációs bicikli", ar:79990, marka:"Kona", leiras:"Magas minőségű és kényelmes." },
 { kategoria:"Konyhai eszközök", nev:"Grill serpenyő", ar:15990, marka:"Tefal", leiras:"Tapadásmentes bevonat, gyors és egészséges sütés." },
 { kategoria:"Konyhai eszközök", nev:"Habverő", ar:7990, marka:"KitchenAid", leiras:"Professzionális habverő, erőteljes motorral." },
 { kategoria:"Konyhai eszközök", nev:"Hűtő", ar:99900, marka:"Whirlpool", leiras:"Extra nagy tárolóhely és energiatakarékos működés." },
 { kategoria:"Bútorok", nev:"Íróasztal", ar:18900, marka:"Lepo", leiras:"Ergonomikus, tágas munkafelület." },
 { kategoria:"Elektronikai termékek", nev:"Játék konzol", ar:79990, marka:"PlayStation", leiras:"Legújabb játékokhoz optimalizált konzol." },
 { kategoria:"Bútorok", nev:"Kávézóasztal", ar:14990, marka:"West Elm", leiras:"Modern design, praktikus tárolás." },
 { kategoria:"Konyhai eszközök", nev:"Kenyeret sütő", ar:24990, marka:"Philips", leiras:"Automatikus programok, finom kenyeret süt." },
 { kategoria:"Bútorok", nev:"Kétszemélyes kanapé", ar:69900, marka:"IKEA", leiras:"Kényelmes, egyszerű dizájn." },
 { kategoria:"Sportfelszerelések", nev:"Kézilabda", ar:2490, marka:"Select", leiras:"Magas minőségű, profi használatra." },
 { kategoria:"Elektronikai termékek", nev:"Laptop", ar:129900, marka:"Dell", leiras:"Erőteljes processzor és nagy teljesítményű grafika." },
 { kategoria:"Konyhai eszközök", nev:"Leves főző", ar:29990, marka:"Philips", leiras:"Automatikus főzés, könnyen tisztítható." },
 { kategoria:"Elektronikai termékek", nev:"Okosóra", ar:24990, marka:"Garmin", leiras:"Fitnesz- és egészségfigyelés, hosszú akkumulátor idő." },
 { kategoria:"Elektronikai termékek", nev:"Okostelefon", ar:79990, marka:"Samsung", leiras:"Új modell, nagy kijelzővel, és hosszú üzemidővel." },
 { kategoria:"Sportfelszerelések", nev:"Sílécek", ar:69990, marka:"Völkl", leiras:"Alpine síeléshez tökéletes választás." },
 { kategoria:"Sportfelszerelések", nev:"Snowboard", ar:89990, marka:"Burton", leiras:"Tartós, könnyen irányítható deszka." },
 { kategoria:"Bútorok", nev:"Szék", ar:12990, marka:"Habufa", leiras:"Ergonomikus, kényelmes ülőalkalmatosság." },
 { kategoria:"Bútorok", nev:"Szekrény", ar:39900, marka:"IKEA", leiras:"Tágas, sokféle elrendezési lehetőséggel." },
 { kategoria:"Elektronikai termékek", nev:"Tablet", ar:59990, marka:"Apple", leiras:"Rendkívül gyors, Retina kijelzővel." },
 { kategoria:"Bútorok", nev:"Tároló szekrény", ar:21990, marka:"Blanco", leiras:"Nagy tárolókapacitás, jól zárható." },
 { kategoria:"Konyhai eszközök", nev:"Teafőző", ar:19990, marka:"Tefal", leiras:"Digitális vezérlés, tökéletes teák." },
 { kategoria:"Sportfelszerelések", nev:"Teniszütő", ar:15990, marka:"Wilson", leiras:"Erőteljes ütés és stabil fogás." },
 { kategoria:"Elektronikai termékek", nev:"Tévé", ar:229000, marka:"Sony", leiras:"Ultra HD, LED kijelző, és okos funkciók." },
 { kategoria:"Konyhai eszközök", nev:"Turmixgép", ar:14990, marka:"Blender", leiras:"Erős motor, sokféle program." },
 { kategoria:"Sportfelszerelések", nev:"Úszódeszka", ar:3990, marka:"Mares", leiras:"Segít a gyorsabb úszásban." }
]